/*
 * generated by Xtext 2.12.0
 */
package org.xtext.markHammil.mh.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HammilDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/markHammil/mh/parser/antlr/internal/InternalHammilDSL.tokens");
	}
}
