<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="markdown" nsURI="http://www.example.org/markdown" nsPrefix="markdown">
  <eClassifiers xsi:type="ecore:EClass" name="File">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        eType="#//EmphasisExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IntObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbColumn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IntObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tablelines" lowerBound="1"
        upperBound="-1" eType="#//TableLine" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableLine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbColumn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IntObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellContent" lowerBound="1"
        upperBound="-1" eType="#//TextExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HorizontalExpression" eSuperTypes="#//TextExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startingValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IntObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listContent" lowerBound="1"
        upperBound="-1" eType="#//TextExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuoteExpression" eSuperTypes="#//TextExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textexpression" lowerBound="1"
        eType="#//TextExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineBreakExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EmphasisExpression" eSuperTypes="#//TextExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ItalicExpression" eSuperTypes="#//EmphasisExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        upperBound="-1" eType="#//EmphasisExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StrongExpression" eSuperTypes="#//EmphasisExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        upperBound="-1" eType="#//EmphasisExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScratchExpression" eSuperTypes="#//EmphasisExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        upperBound="-1" eType="#//EmphasisExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextBloc" eSuperTypes="#//EmphasisExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HTMLExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" lowerBound="1" eType="#//TextBloc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//TextBloc"/>
  </eClassifiers>
</ecore:EPackage>
