/*
 * generated by Xtext 2.12.0
 */
package org.xtext.markhamill.mh.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHamillDslScopeProvider extends DelegatingScopeProvider {
}
