/**
 * generated by Xtext 2.12.0
 */
package markHammil.mm.myDsl.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import markHammil.mm.myDsl.LineExpression;
import markHammil.mm.myDsl.MyDslFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Line Expression</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class LineExpressionTest extends TestCase {

	/**
	 * The fixture for this Line Expression test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineExpression fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(LineExpressionTest.class);
	}

	/**
	 * Constructs a new Line Expression test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public LineExpressionTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Line Expression test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(LineExpression fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Line Expression test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineExpression getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MyDslFactory.eINSTANCE.createLineExpression());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //LineExpressionTest
