/**
 * generated by Xtext 2.12.0
 */
package markHammil.mm.myDsl.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import markHammil.mm.myDsl.MyDslFactory;
import markHammil.mm.myDsl.RefExpression;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Ref Expression</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class RefExpressionTest extends TestCase {

	/**
	 * The fixture for this Ref Expression test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RefExpression fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(RefExpressionTest.class);
	}

	/**
	 * Constructs a new Ref Expression test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RefExpressionTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Ref Expression test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(RefExpression fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Ref Expression test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected RefExpression getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MyDslFactory.eINSTANCE.createRefExpression());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //RefExpressionTest
