/**
 * generated by Xtext 2.12.0
 */
package org.xtext.markhamill.mh.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import markdown.Expression;
import markdown.File;
import markdown.TableExpression;
import markdown.TableLine;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.markhamill.mh.services.HamillDslGrammarAccess;

@SuppressWarnings("all")
public class HamillDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private HamillDslGrammarAccess _hamillDslGrammarAccess;
  
  protected void _format(final File file, @Extension final IFormattableDocument document) {
    EList<Expression> _expression = file.getExpression();
    for (final Expression expression : _expression) {
      document.<Expression>format(expression);
    }
  }
  
  protected void _format(final TableExpression tableExpression, @Extension final IFormattableDocument document) {
    EList<TableLine> _tablelines = tableExpression.getTablelines();
    for (final TableLine tableLine : _tablelines) {
      document.<TableLine>format(tableLine);
    }
  }
  
  public void format(final Object tableExpression, final IFormattableDocument document) {
    if (tableExpression instanceof XtextResource) {
      _format((XtextResource)tableExpression, document);
      return;
    } else if (tableExpression instanceof TableExpression) {
      _format((TableExpression)tableExpression, document);
      return;
    } else if (tableExpression instanceof File) {
      _format((File)tableExpression, document);
      return;
    } else if (tableExpression instanceof EObject) {
      _format((EObject)tableExpression, document);
      return;
    } else if (tableExpression == null) {
      _format((Void)null, document);
      return;
    } else if (tableExpression != null) {
      _format(tableExpression, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(tableExpression, document).toString());
    }
  }
}
