/**
 * generated by Xtext 2.12.0
 */
package markHammil.mm.myDsl.impl;

import markHammil.mm.myDsl.Header2Expression;
import markHammil.mm.myDsl.MyDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Header2 Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class Header2ExpressionImpl extends HeaderExpressionImpl implements Header2Expression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Header2ExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.HEADER2_EXPRESSION;
  }

} //Header2ExpressionImpl
