/**
 * generated by Xtext 2.12.0
 */
package markHammil.mm.ide;

import markHammil.mm.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
