/**
 * generated by Xtext 2.12.0
 */
package markHammil.mm.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Break Line Expression B</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see markHammil.mm.myDsl.MyDslPackage#getBreakLineExpressionB()
 * @model
 * @generated
 */
public interface BreakLineExpressionB extends BreakLineExpression
{
} // BreakLineExpressionB
