/**
 * generated by Xtext 2.12.0
 */
package markHammil.mm.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Break Line Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see markHammil.mm.myDsl.MyDslPackage#getBreakLineExpression()
 * @model
 * @generated
 */
public interface BreakLineExpression extends Expression
{
} // BreakLineExpression
