/**
 * generated by Xtext 2.12.0
 */
package markHammil.mm.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Header Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link markHammil.mm.myDsl.HeaderExpression#getTitle <em>Title</em>}</li>
 * </ul>
 *
 * @see markHammil.mm.myDsl.MyDslPackage#getHeaderExpression()
 * @model
 * @generated
 */
public interface HeaderExpression extends Expression
{
  /**
	 * Returns the value of the '<em><b>Title</b></em>' containment reference list.
	 * The list contents are of type {@link markHammil.mm.myDsl.EmphasisExpression}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Title</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Title</em>' containment reference list.
	 * @see markHammil.mm.myDsl.MyDslPackage#getHeaderExpression_Title()
	 * @model containment="true"
	 * @generated
	 */
  EList<EmphasisExpression> getTitle();

} // HeaderExpression
