/**
 * generated by Xtext 2.12.0
 */
package markHammil.mm.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Header6 Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see markHammil.mm.myDsl.MyDslPackage#getHeader6Expression()
 * @model
 * @generated
 */
public interface Header6Expression extends HeaderExpression
{
} // Header6Expression
