/**
 * generated by Xtext 2.12.0
 */
package markHammil.mm.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Header</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link markHammil.mm.myDsl.Header#getTitle <em>Title</em>}</li>
 * </ul>
 *
 * @see markHammil.mm.myDsl.MyDslPackage#getHeader()
 * @model
 * @generated
 */
public interface Header extends Expression
{
  /**
	 * Returns the value of the '<em><b>Title</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Title</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Title</em>' containment reference.
	 * @see #setTitle(EmphasisExpression)
	 * @see markHammil.mm.myDsl.MyDslPackage#getHeader_Title()
	 * @model containment="true"
	 * @generated
	 */
  EmphasisExpression getTitle();

  /**
	 * Sets the value of the '{@link markHammil.mm.myDsl.Header#getTitle <em>Title</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Title</em>' containment reference.
	 * @see #getTitle()
	 * @generated
	 */
  void setTitle(EmphasisExpression value);

} // Header
