/**
 * generated by Xtext 2.12.0
 */
package markHammil.mm.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scratch Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see markHammil.mm.myDsl.MyDslPackage#getScratchExpression()
 * @model
 * @generated
 */
public interface ScratchExpression extends EmphasisExpression
{
} // ScratchExpression
