/**
 * generated by Xtext 2.12.0
 */
package markHammil.mm.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see markHammil.mm.myDsl.MyDslPackage#getTextExpression()
 * @model
 * @generated
 */
public interface TextExpression extends EObject
{
} // TextExpression
